### ISSUE TITLE
FR: add support for ssh over http proxy

### ISSUE THREAD

**Issue by hellt** [mysocketio/mysocketctl-go#23]
It has been discovered that SSH can be established over the HTTP proxies. This is a huge life saver for running mysocketio in the corp environments where external SSH is usually blocked and instead the HTTP proxy is being used.

Go's SSH client can use the Dialer that uses HTTP proxy to somewhat stitch the two. This project has an implementation that has been tested to work https://github.com/blacknon/go-sshlib/blob/master/proxy.go

It would be awesome for mysocketctl to expose a flag `--http-proxy addr:port` so that we could happily use mysocketctl in corp environments

**Comment by atoonk** [comment]
this functionality was added see PR (now) linked to this feature request.
This is using the proxy CONNECT feature.

tunnel SSH through a proxy using ```--proxy http://localhost:3128```
example: 
```
mysocketctl tunnel connect -p 45331 --proxy http://localhost:3128 \
 -s ca58c819-7ca2-4f81-b6c8-649a2d72c032 \
 -t 9356f1e5-bd89-4476-81de-4c5934760a11  
```

**Comment by hellt** [comment]
thanks @atoonk @btoonk!
